### ISSUE TITLE
Feature Request: Start Application without showing the window

### ISSUE THREAD

**Issue by riscie** [Suyash12mahar/Clipboarder#11]
Hi there!

Cool little tool you are writing there! I really like the idea of syntax highlighting within a clipboard-manager, which is why I gave it a try.
I know you are probably planing a lot of features. Here is my little request: Add an option to start the tool hidden, for when it is placed in autostart.

happy coding! ;)
Riscie

**Comment by suyashmahar** [comment]
Add to next version's checklist! :-) 

Thanks for trying Clipboarder
